const fs = require('fs');
const path = require('path');
const test = require('node:test');
const assert = require('node:assert/strict');
const { getComparableBracket } = require('../shared/comparable-bracket');

const indexHtml = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const indexAccuracyMetaJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-accuracy-meta.js'), 'utf8');
const indexMarketContextJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-market-context.js'), 'utf8');
const indexDistrictContextJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-district-context.js'), 'utf8');
const indexGisHelpersJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-gis-helpers.js'), 'utf8');
const indexPrimaryInteractionsJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-primary-interactions.js'), 'utf8');
const indexMapLinkingJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-map-linking-runtime.js'), 'utf8');
const marketIntelligenceHtml = fs.readFileSync(path.join(__dirname, '..', 'market-intelligence.html'), 'utf8');
const marketIntelligenceJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'market-intelligence.js'), 'utf8');
const accuracyDashboardHtml = fs.readFileSync(path.join(__dirname, '..', 'accuracy-dashboard.html'), 'utf8');
const accuracyDashboardJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'accuracy-dashboard.js'), 'utf8');
const calibrationHtml = fs.readFileSync(path.join(__dirname, '..', 'calibration.html'), 'utf8');
const calibrationJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'calibration.js'), 'utf8');
const exportHtml = fs.readFileSync(path.join(__dirname, '..', 'export.html'), 'utf8');
const exportJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'export.js'), 'utf8');

test('comparable bracket selects the nearest strict lower and upper prices', () => {
  assert.deepEqual(getComparableBracket(1802730, [1868000, 1680000, 2200000, 1500000]), {
    lower: 1680000,
    upper: 1868000
  });
});

test('comparable bracket ignores invalid values and returns null without both sides', () => {
  assert.equal(getComparableBracket(100, [0, -2, 'bad', 90, null]), null);
  assert.equal(getComparableBracket(100, [90, 100]), null);
  assert.equal(getComparableBracket(100, [100, 110]), null);
  assert.equal(getComparableBracket('bad', [90, 110]), null);
});

test('public result keeps Range hidden while retaining the internal bracket calculation', () => {
  assert.match(indexMarketContextJs, /function getComparableBracket\(targetValue, prices\)/);
  assert.match(indexHtml, /const comparableBracket = getComparableBracket\(/);
  assert.match(indexHtml, /const comparableRangeHTML = '';/);
  assert.doesNotMatch(indexHtml, /DLD suggestion/);
  assert.match(indexHtml, /Verified project suggestion/);
});

test('autocomplete controls expose keyboard and listbox semantics', () => {
  assert.match(indexHtml, /role="combobox" aria-autocomplete="list" aria-controls="districtAutocomplete" aria-expanded="false"/);
  assert.match(indexHtml, /id="districtAutocomplete" role="listbox"/);
  assert.match(indexHtml, /id="projectBuildingAutocomplete" role="listbox"/);
  assert.match(indexDistrictContextJs, /function setAutocompleteItem\(item, onSelect\)/);
  assert.match(indexDistrictContextJs, /item\.tabIndex = 0/);
  assert.match(indexDistrictContextJs, /event\.key === 'Enter' \|\| event\.key === ' '/);
});

test('autocomplete lists use a body-level fixed portal', () => {
  assert.match(indexHtml, /\.autocomplete-list\.autocomplete-portal/);
  assert.match(indexHtml, /position: fixed/);
  assert.match(indexDistrictContextJs, /document\.body\.appendChild\(list\)/);
  assert.match(indexDistrictContextJs, /window\.addEventListener\('scroll', repositionVisibleAutocompleteLists, true\)/);
  assert.match(indexDistrictContextJs, /window\.addEventListener\('resize', repositionVisibleAutocompleteLists\)/);
  assert.doesNotMatch(indexHtml, /function setAutocompleteItem\(item, onSelect\)/);
});

test('custom checkboxes preserve native focusability', () => {
  assert.match(indexHtml, /\.checkbox-item:focus-within/);
  assert.match(indexHtml, /\.checkbox-item input \{ position: absolute; width: 1px; height: 1px; opacity: 0; \}/);
  assert.doesNotMatch(indexHtml, /\.checkbox-item input \{ display: none; \}/);
});

test('public pages use semantic headings and safe external links', () => {
  for (const source of [indexHtml, accuracyDashboardHtml, marketIntelligenceHtml]) {
    assert.match(source, /target="_blank" rel="noopener noreferrer"/);
    assert.doesNotMatch(source, /target="_blank"(?! rel="noopener noreferrer")/);
  }
  assert.ok(indexHtml.includes('<script src="/shared/index-accuracy-meta.js"></script>'));
  assert.ok(indexHtml.includes('<script src="/shared/index-calibration-bootstrap.js"></script>'));
  assert.ok(indexHtml.indexOf('/shared/index-accuracy-meta.js') < indexHtml.indexOf('/shared/index-calibration-bootstrap.js'));
  assert.ok(indexHtml.indexOf('/shared/index-calibration-bootstrap.js') < indexHtml.indexOf('/shared/index-market-context.js'));
  assert.doesNotMatch(indexHtml, /let AQAR_ACTIVE_CALIBRATION\s*=/);
  assert.ok(indexAccuracyMetaJs.includes('AQAR_ACTIVE_CALIBRATION = AQAR_CALIBRATION_DEFAULTS.createDefaultCalibrationConfig()'));
  assert.ok(indexAccuracyMetaJs.includes('AQAR_V21_SHADOW_CONFIG = AQAR_V21_SHADOW_MULTIPLIERS.createNeutralConfig()'));
  const calibrationBootstrapJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-calibration-bootstrap.js'), 'utf8');
  assert.ok(calibrationBootstrapJs.includes('async function loadCalibrationConfig()'));
  assert.ok(calibrationBootstrapJs.includes('function getCalibrationForProperty(propertyType)'));
  assert.ok(indexHtml.includes('<script src="/shared/index-runtime-state.js"></script>'));
  assert.ok(indexHtml.indexOf('/shared/index-calibration-bootstrap.js') < indexHtml.indexOf('/shared/index-runtime-state.js'));
  assert.ok(indexHtml.indexOf('/shared/index-runtime-state.js') < indexHtml.indexOf('/shared/index-district-map-core.js'));
  assert.ok(indexHtml.indexOf('/shared/index-district-map-core.js') < indexHtml.indexOf('/shared/index-market-context.js'));
  const districtMapCoreJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-district-map-core.js'), 'utf8');
  assert.ok(districtMapCoreJs.includes('async function loadDistrictCoords()'));
  assert.ok(districtMapCoreJs.includes('function getDistrictCoords(district)'));
  assert.ok(districtMapCoreJs.includes('function escapeMapHtml(value)'));
  assert.doesNotMatch(indexHtml, /const UAE_DISTRICTS = \{/);
  assert.doesNotMatch(indexHtml, /const FALLBACK_COORDS = \{/);
  assert.doesNotMatch(indexHtml, /let districtCoordsMap = \{\}/);
  assert.doesNotMatch(indexHtml, /const MAP_DISTRICT_MATCH_MAX_KM = 1\.5/);
  const runtimeStateJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-runtime-state.js'), 'utf8');
  assert.ok(runtimeStateJs.includes('const UAE_DISTRICTS = {'));
  assert.ok(runtimeStateJs.includes('const FALLBACK_COORDS = {'));
  assert.ok(runtimeStateJs.includes('let districtCoordsMap = {}'));
  assert.ok(runtimeStateJs.includes('const MAP_DISTRICT_MATCH_MAX_KM = 1.5'));
  assert.ok(indexHtml.includes('<script src="/shared/index-market-context.js"></script>'));
  assert.ok(indexHtml.includes('<script src="/shared/index-district-context.js"></script>'));
  assert.ok(indexHtml.includes('<script src="/shared/index-gis-helpers.js"></script>'));
  assert.ok(indexHtml.includes('<script src="/shared/index-primary-interactions.js"></script>'));
  assert.ok(indexPrimaryInteractionsJs.includes("addEventListener('click', runValuation)"));
  assert.ok(indexPrimaryInteractionsJs.includes("addEventListener('change', onPropertyTypeChange)"));
  assert.ok(indexPrimaryInteractionsJs.includes("closest?.('[data-action]')"));
  assert.ok(indexPrimaryInteractionsJs.includes("action !== 'review-inputs' && action !== 'new-valuation'"));
  assert.match(indexHtml, /data-action="review-inputs"/);
  assert.match(indexHtml, /data-action="new-valuation"/);
  assert.doesNotMatch(indexHtml, /onclick="document\.getElementById\('resultSection'\)/);
  assert.ok(indexDistrictContextJs.includes('async function loadDistrictsFromDLD()'));
  assert.ok(indexDistrictContextJs.includes('function filterDistricts(q)'));
  assert.ok(indexDistrictContextJs.includes('function filterProjectBuildings(q)'));
  assert.doesNotMatch(indexHtml, /function loadDistrictsFromDLD\(\)/);
  assert.doesNotMatch(indexHtml, /function getCalibrationForProperty\(propertyType\)/);
  assert.doesNotMatch(indexHtml, /async function loadCalibrationConfig\(\)/);
  assert.doesNotMatch(indexHtml, /async function loadDistrictCoords\(\)/);
  assert.doesNotMatch(indexHtml, /function getDistrictCoords\(district\)/);
  assert.doesNotMatch(indexHtml, /function escapeMapHtml\(value\)/);
  assert.doesNotMatch(indexHtml, /function filterDistricts\(q\)/);
  assert.ok(indexGisHelpersJs.includes('function getGISRadiusMeters()'));
  assert.ok(indexGisHelpersJs.includes('function updateGISRadiusContext(radius = getGISRadiusMeters(), count = null)'));
  assert.ok(indexGisHelpersJs.includes('function haversineDistance(lat1, lng1, lat2, lng2)'));
  assert.ok(indexGisHelpersJs.includes('function getFacilityLabel(k)'));
  assert.ok(indexGisHelpersJs.includes('function getFacilityIcon(k)'));
  assert.doesNotMatch(indexHtml, /function getGISRadiusMeters\(\)/);
  assert.doesNotMatch(indexHtml, /function haversineDistance\(lat1, lng1, lat2, lng2\)/);
  assert.doesNotMatch(indexHtml, /onchange="onCityChange\(\)"/);
  assert.doesNotMatch(indexHtml, /onchange="onPropertyTypeChange\(\)"/);
  assert.doesNotMatch(indexHtml, /oninput="updateExtraFieldVisibility\(\)"/);
  assert.doesNotMatch(indexHtml, /onclick="(scrapeRealData|runValuation|resetAll)\(\)"/);
  assert.ok(indexHtml.includes('class="gis-impact-label"'));
  assert.ok(indexHtml.includes('class="gis-impact-detail"'));
  assert.ok(indexHtml.includes('class="market-status-detail"'));
  assert.ok(indexHtml.includes('class="market-status-review"'));
  assert.ok(indexHtml.includes('class="gis-map-unavailable"'));
  assert.ok(indexMapLinkingJs.includes('class="project-map-label"'));
  assert.ok(indexMapLinkingJs.includes('class="project-map-popup-source"'));
  assert.ok(indexMapLinkingJs.includes('class="project-map-source"'));
  assert.ok(indexHtml.includes('class="gis-facilities-title"'));
  assert.ok(indexHtml.includes('class="gis-facilities-list"'));
  assert.ok(indexHtml.includes('class="gis-score-display"'));
  assert.ok(indexHtml.includes('class="gis-map-container"'));
  assert.ok(indexHtml.includes('class="poi-popup-distance"'));
  assert.ok(indexHtml.includes("const poiClass = colors[p.type] ? `poi-${p.type}` : 'poi-default';"));
  assert.ok(indexHtml.includes('class="poi-marker ${poiClass}"'));
  assert.ok(indexMapLinkingJs.includes('async function resolveDistrictCoords(district)'));
  assert.ok(indexMapLinkingJs.includes('async function selectDistrict(d)'));
  assert.ok(indexMapLinkingJs.includes('function updateDistrictFromMapPoint(lat, lng)'));
  assert.doesNotMatch(indexHtml, /class="poi-marker" style="--poi-color:/);
  assert.ok(indexHtml.includes('.observation-status.success'));
  assert.ok(indexHtml.includes('.observation-status.warning'));
  assert.ok(indexHtml.includes('class="result-method-status ${statusClass}"'));
  assert.doesNotMatch(indexHtml, /status\.style\.color/);
  assert.doesNotMatch(indexHtml, /<b style="color:\$\{color\};font-size:10px">/);
  assert.doesNotMatch(indexHtml, /<div style="background:#d4920e;color:#06111d/);
  assert.doesNotMatch(indexHtml, /<div style="background:\$\{colors\[p\.type\]/);
  assert.doesNotMatch(indexHtml, /<div style="font-size:12px;font-weight:700;color:var\(--gold\);margin-bottom:6px">📊 Nearby Facilities<\/div>/);
  assert.doesNotMatch(indexHtml, /id="gisFacilitiesList"[^>]+style="font-size:11px;color:var\(--muted\);line-height:1\.8"/);
  assert.doesNotMatch(indexHtml, /id="gisMap"[^>]+style="margin-top:10px;height:320px/);
  assert.doesNotMatch(indexHtml, /<span style="font-size:10px;color:#888;">\$\{\(p\.distance\*1000\)/);
  assert.match(indexHtml, /\.js-hidden \{ display: none; \}/);
  assert.match(indexHtml, /<div class="row js-hidden" id="rowPropertyAreas">/);
  assert.match(indexHtml, /<div class="row js-hidden" id="rowProjectBuilding">/);
  assert.match(indexHtml, /<div class="row js-hidden" id="gisCoordsRow"/);
  assert.doesNotMatch(indexHtml, /(?:rowPropertyAreas|fgBua|fgPlotArea|fgLastRenovation|rowProjectBuilding|gisCoordsRow)"[^>]+style="display:none"/);
  assert.doesNotMatch(indexHtml, /getElementById\('(rowPropertyAreas|fgBua|fgPlotArea|fgLastRenovation|rowProjectBuilding|gisCoordsRow)'\)\.style\.display/);
  assert.match(indexHtml, /\.gis-result-panel\.is-visible \{ display: block; \}/);
  assert.match(indexHtml, /\.gis-project-label\.is-visible \{ display: block; \}/);
  assert.match(indexHtml, /container\.classList\.add\('is-visible'\)/);
  assert.doesNotMatch(indexHtml, /(?:gisResult|gisProjectLabel).*style\.display/);
  assert.doesNotMatch(indexDistrictContextJs, /row\.style\.display = visibility\.projectBuilding/);
  assert.match(indexHtml, /\.autocomplete-list\.is-visible \{ display: block; \}/);
  assert.match(indexHtml, /\.autocomplete-list \.item\.empty-state \{ color: var\(--muted\); cursor: default; \}/);
  assert.match(indexHtml, /\.project-building-notice\.attention \{ color: var\(--gold\); \}/);
  assert.match(indexHtml, /\.project-building-notice\.verified \{ color: var\(--green\); \}/);
  assert.ok(indexDistrictContextJs.includes("function setProjectBuildingNotice(notice, text, tone)"));
  assert.ok(indexDistrictContextJs.includes("empty.className = 'item empty-state'"));
  assert.doesNotMatch(indexDistrictContextJs, /notice\.style\.color|empty\.style\.cssText/);
  assert.doesNotMatch(indexDistrictContextJs, /list\.style\.display|c\.style\.display/);
  assert.doesNotMatch(indexHtml, /scoreDisplay\.innerHTML = `?[^`]*style="color:var\(--gold\)"/);
  assert.doesNotMatch(indexHtml, /<span style="color:var\(--muted\)">🔍 Checking market data/);
  assert.ok(indexMarketContextJs.includes('function buildMarketContextHTML(result, propData)'));
  assert.ok(indexMarketContextJs.includes('class="market-indicators"'));
  assert.doesNotMatch(indexMarketContextJs, /<div style="margin-top:12px;padding-top:10px/);
  assert.match(indexHtml, /\.market-indicators \{ margin-top: 12px; padding-top: 10px; border-top: 1px solid rgba\(255,255,255,0\.08\); \}/);
  assert.match(indexHtml, /width: var\(--confidence-width, 0%\)/);
  assert.ok(indexHtml.includes("style.setProperty('--confidence-width', `${result.confidencePct}%`)"));
  assert.doesNotMatch(indexHtml, /style="(?:--confidence-width|width):/);
  assert.ok(indexMarketContextJs.includes('function renderEvidenceState(state, container, detail = \'\')'));
  assert.ok(indexMarketContextJs.includes('escapeMapHtml(propData.district || \'the selected area\')'));
  assert.doesNotMatch(indexHtml, /function buildMarketContextHTML\(result, propData\)/);
  assert.ok(accuracyDashboardHtml.includes('<h1 class="miayaar-page-title">Accuracy Dashboard</h1>'));
  assert.ok(accuracyDashboardHtml.includes('<script src="/shared/accuracy-dashboard.js"></script>'));
  assert.ok(accuracyDashboardHtml.includes('.refresh-bar-heading'));
  assert.ok(accuracyDashboardHtml.includes('.refresh-actions'));
  assert.ok(accuracyDashboardHtml.includes('.dashboard-footer-links'));
  assert.ok(accuracyDashboardHtml.includes('.table-ref-cell'));
  assert.ok(accuracyDashboardHtml.includes('.table-date-cell'));
  assert.doesNotMatch(accuracyDashboardHtml, /<[^>]+style="/);
  assert.ok(accuracyDashboardHtml.includes('id="loadSavedDataButton"'));
  assert.doesNotMatch(accuracyDashboardHtml, /<script>\s*[\s\S]*<\/script>/);
  assert.ok(accuracyDashboardJs.includes('function updateTable(properties)'));
  assert.ok(accuracyDashboardJs.includes("document.getElementById('loadSavedDataButton')?.addEventListener"));
  assert.ok(accuracyDashboardJs.includes('class="loading loading-error"'));
  assert.ok(accuracyDashboardJs.includes('class="table-ref-cell"'));
  assert.ok(accuracyDashboardJs.includes('class="table-city-cell"'));
  assert.ok(accuracyDashboardJs.includes('class="table-date-cell"'));
  assert.ok(accuracyDashboardJs.includes('class="table-summary"'));
  assert.doesNotMatch(accuracyDashboardJs, /style="/);
  assert.ok(calibrationHtml.includes('<script src="/shared/calibration.js"></script>'));
  assert.doesNotMatch(calibrationHtml, /<script>\s*[\s\S]*<\/script>/);
  assert.doesNotMatch(calibrationHtml, /onclick=/);
  assert.ok(calibrationJs.includes('async function request(method=\'GET\', body)'));
  assert.ok(calibrationJs.includes('data-action="add-project-multiplier"'));
  assert.ok(calibrationJs.includes("$('saveButton').addEventListener('click', saveConfig)"));
  assert.ok(calibrationHtml.includes('.project-multiplier-row'));
  assert.ok(calibrationHtml.includes('.shadow-project-row'));
  assert.ok(calibrationHtml.includes('.shadow-band-row'));
  assert.ok(calibrationHtml.includes('.shadow-add-row'));
  assert.ok(calibrationHtml.includes('.calibration-input-row'));
  assert.ok(calibrationHtml.includes('.calibration-group-heading'));
  assert.ok(calibrationJs.includes('class="field-grid shadow-project-row"'));
  assert.ok(calibrationJs.includes('class="field-grid shadow-band-row"'));
  assert.ok(calibrationJs.includes('class="field-grid shadow-add-row"'));
  assert.ok(calibrationJs.includes('class="calibration-input-row"'));
  assert.ok(calibrationJs.includes('class="panel-note calibration-group-heading"'));
  assert.ok(calibrationJs.includes("wrapper.className = 'field-grid project-multiplier-row'"));
  assert.doesNotMatch(calibrationJs, /style="(?:grid-template-columns|display)/);
  assert.doesNotMatch(calibrationJs, /style\.cssText/);
  assert.ok(marketIntelligenceHtml.includes('<h1 class="miayaar-page-title">Market Intelligence</h1>'));
  assert.ok(marketIntelligenceHtml.includes('<script src="/shared/market-intelligence.js"></script>'));
  assert.ok(marketIntelligenceHtml.includes('.methodology-panel'));
  assert.ok(marketIntelligenceHtml.includes('.dashboard-footer-links'));
  assert.doesNotMatch(marketIntelligenceHtml, /<[^>]+style="/);
  assert.doesNotMatch(marketIntelligenceHtml, /<script>\s*[\s\S]*<\/script>/);
  assert.ok(marketIntelligenceJs.includes('function renderInvestmentTable()'));
  assert.ok(marketIntelligenceJs.includes("document.getElementById('growthPeriodFilter').addEventListener"));
  assert.ok(marketIntelligenceJs.includes('class="loading loading-error"'));
  assert.doesNotMatch(marketIntelligenceJs, /style="/);
  assert.ok(exportHtml.includes('<h1 class="miayaar-page-title">Data Export</h1>'));
  assert.match(exportHtml, /<meta name="viewport" content="width=device-width, initial-scale=1\.0">/);
  assert.ok(exportHtml.includes('<script src="/shared/export.js"></script>'));
  assert.ok(exportHtml.includes('id="exportCsvButton"'));
  assert.ok(exportHtml.includes('id="exportJsonButton"'));
  assert.doesNotMatch(exportHtml, /<script>\s*[\s\S]*<\/script>/);
  assert.ok(exportJs.includes('function csvCell(value)'));
  assert.ok(exportJs.includes("typeof value === 'string'"));
  assert.ok(exportJs.includes("safeText.replace(/\"/g, '\"\"')"));
  assert.ok(exportJs.includes("/^[=+\\-@]/.test(text)"));
  assert.ok(exportJs.includes('class="accuracy-value"'));
  assert.ok(exportHtml.includes('.stats .accuracy-value'));
  assert.ok(exportHtml.includes('class="dashboard-link"'));
  assert.doesNotMatch(exportJs, /<b style="color:#00b86e">/);
  assert.doesNotMatch(exportHtml, /href="\/accuracy-dashboard" style=/);
});

test('Market Intelligence tables stay intact inside horizontally scrollable cards', () => {
  assert.match(marketIntelligenceHtml, /\.table-scroll/);
  assert.match(marketIntelligenceHtml, /overflow-x: auto/);
  assert.match(marketIntelligenceHtml, /\.table-scroll table \{ min-width: 520px; \}/);
  assert.match(marketIntelligenceJs, /role="region" tabindex="0" aria-label="Top 10 Investment Districts table"/);
  assert.doesNotMatch(marketIntelligenceHtml, /\.table-scroll thead \{/);
  assert.doesNotMatch(marketIntelligenceHtml, /data-label="District"/);
});
