const fs = require('fs');
const path = require('path');
const test = require('node:test');
const assert = require('node:assert/strict');
const { getComparableBracket } = require('../shared/comparable-bracket');

const indexHtml = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const indexPageCss = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-page.css'), 'utf8');
const brandCss = fs.readFileSync(path.join(__dirname, '..', 'shared', 'miayaar-brand.css'), 'utf8');
const inlineValidatorJs = fs.readFileSync(path.join(__dirname, '..', 'scripts', 'validate-inline-js.js'), 'utf8');
const indexAccuracyMetaJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-accuracy-meta.js'), 'utf8');
const indexMarketContextJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-market-context.js'), 'utf8');
const indexResultRenderingJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-result-rendering-runtime.js'), 'utf8');
const indexObservationRuntimeJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-observation-runtime.js'), 'utf8');
const indexRunValuationRuntimeJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-run-valuation-runtime.js'), 'utf8');
const indexResetHistoryRuntimeJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-reset-history-runtime.js'), 'utf8');
const indexMetadataUiRuntimeJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-metadata-ui-runtime.js'), 'utf8');
const indexDomBootstrapRuntimeJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-dom-bootstrap-runtime.js'), 'utf8');
const indexDistrictContextJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-district-context.js'), 'utf8');
const indexGisHelpersJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-gis-helpers.js'), 'utf8');
const indexPrimaryInteractionsJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-primary-interactions.js'), 'utf8');
const indexMapLinkingJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-map-linking-runtime.js'), 'utf8');
const indexFieldViewJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-field-view-runtime.js'), 'utf8');
const indexMapMarkerJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-map-marker-runtime.js'), 'utf8');
const indexGisFetchJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-gis-fetch-runtime.js'), 'utf8');
const indexGisFetchCoordinatorJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-gis-fetch-coordinator.js'), 'utf8');
const indexScrapeRuntimeJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-scrape-runtime.js'), 'utf8');
const indexGisDisplayJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-gis-display-runtime.js'), 'utf8');
const indexMarketCalculationJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-market-calculation-helpers.js'), 'utf8');
const indexPropertyDataJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-property-data-runtime.js'), 'utf8');
const indexSalesApproachJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-sales-approach-runtime.js'), 'utf8');
const indexIncomeApproachJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-income-approach-runtime.js'), 'utf8');
const indexCostApproachJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-cost-approach-runtime.js'), 'utf8');
const indexDcfApproachJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-dcf-approach-runtime.js'), 'utf8');
const indexWeightedRuntimeJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-weighted-runtime.js'), 'utf8');
const marketIntelligenceHtml = fs.readFileSync(path.join(__dirname, '..', 'market-intelligence.html'), 'utf8');
const marketIntelligenceCss = fs.readFileSync(path.join(__dirname, '..', 'shared', 'market-intelligence-page.css'), 'utf8');
const marketIntelligenceJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'market-intelligence.js'), 'utf8');
const accuracyDashboardHtml = fs.readFileSync(path.join(__dirname, '..', 'accuracy-dashboard.html'), 'utf8');
const accuracyDashboardCss = fs.readFileSync(path.join(__dirname, '..', 'shared', 'accuracy-dashboard-page.css'), 'utf8');
const accuracyDashboardJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'accuracy-dashboard.js'), 'utf8');
const calibrationHtml = fs.readFileSync(path.join(__dirname, '..', 'calibration.html'), 'utf8');
const calibrationCss = fs.readFileSync(path.join(__dirname, '..', 'shared', 'calibration-page.css'), 'utf8');
const calibrationJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'calibration.js'), 'utf8');
const exportHtml = fs.readFileSync(path.join(__dirname, '..', 'export.html'), 'utf8');
const exportCss = fs.readFileSync(path.join(__dirname, '..', 'shared', 'export-page.css'), 'utf8');
const exportJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'export.js'), 'utf8');

test('comparable bracket selects the nearest strict lower and upper prices', () => {
  assert.deepEqual(getComparableBracket(1802730, [1868000, 1680000, 2200000, 1500000]), {
    lower: 1680000,
    upper: 1868000
  });
});

test('comparable bracket ignores invalid values and returns null without both sides', () => {
  assert.equal(getComparableBracket(100, [0, -2, 'bad', 90, null]), null);
  assert.equal(getComparableBracket(100, [90, 100]), null);
  assert.equal(getComparableBracket(100, [100, 110]), null);
  assert.equal(getComparableBracket('bad', [90, 110]), null);
});

test('public result keeps Range hidden while retaining the internal bracket calculation', () => {
  assert.match(indexMarketContextJs, /function getComparableBracket\(targetValue, prices\)/);
  assert.match(indexResultRenderingJs, /const comparableBracket = getComparableBracket\(/);
  assert.match(indexResultRenderingJs, /const comparableRangeHTML = '';/);
  assert.doesNotMatch(indexHtml, /DLD suggestion/);
  assert.match(indexResultRenderingJs, /Verified project suggestion/);
});

test('autocomplete controls expose keyboard and listbox semantics', () => {
  assert.match(indexHtml, /role="combobox" aria-autocomplete="list" aria-controls="districtAutocomplete" aria-expanded="false"/);
  assert.match(indexHtml, /id="districtAutocomplete" role="listbox"/);
  assert.match(indexHtml, /id="projectBuildingAutocomplete" role="listbox"/);
  assert.match(indexDistrictContextJs, /function setAutocompleteItem\(item, onSelect\)/);
  assert.match(indexDistrictContextJs, /item\.tabIndex = 0/);
  assert.match(indexDistrictContextJs, /event\.key === 'Enter' \|\| event\.key === ' '/);
});

test('autocomplete lists use a body-level fixed portal', () => {
  assert.match(indexPageCss, /\.autocomplete-list\.autocomplete-portal/);
  assert.match(indexPageCss, /position: fixed/);
  assert.match(indexDistrictContextJs, /document\.body\.appendChild\(list\)/);
  assert.match(indexDistrictContextJs, /window\.addEventListener\('scroll', repositionVisibleAutocompleteLists, true\)/);
  assert.match(indexDistrictContextJs, /window\.addEventListener\('resize', repositionVisibleAutocompleteLists\)/);
  assert.doesNotMatch(indexHtml, /function setAutocompleteItem\(item, onSelect\)/);
});

test('custom checkboxes preserve native focusability', () => {
  assert.match(indexPageCss, /\.checkbox-item:focus-within/);
  assert.match(indexPageCss, /\.checkbox-item input \{ position: absolute; width: 1px; height: 1px; opacity: 0; \}/);
  assert.doesNotMatch(indexPageCss, /\.checkbox-item input \{ display: none; \}/);
});

test('public pages use semantic headings and safe external links', () => {
  for (const source of [indexHtml, accuracyDashboardHtml, marketIntelligenceHtml]) {
    assert.match(source, /target="_blank" rel="noopener noreferrer"/);
    assert.doesNotMatch(source, /target="_blank"(?! rel="noopener noreferrer")/);
  }
  const externalPageStyles = [
    [indexHtml, '/shared/index-page.css'],
    [marketIntelligenceHtml, '/shared/market-intelligence-page.css'],
    [accuracyDashboardHtml, '/shared/accuracy-dashboard-page.css'],
    [calibrationHtml, '/shared/calibration-page.css'],
    [exportHtml, '/shared/export-page.css']
  ];
  for (const [source, href] of externalPageStyles) {
    assert.ok(source.includes(`<link rel="stylesheet" href="${href}" />`));
    assert.doesNotMatch(source, /<style\b/);
    assert.doesNotMatch(source, /\sstyle\s*=/);
  }
  assert.ok(indexHtml.includes('<script src="/shared/index-accuracy-meta.js"></script>'));
  assert.match(brandCss, /\.miayaar-brand-lockup\s*\{/);
  assert.match(brandCss, /\.miayaar-brand-lockup::after\s*\{[\s\S]*height:\s*28%[\s\S]*background:\s*linear-gradient\([\s\S]*#07111f 100%/);
  assert.doesNotMatch(brandCss, /\.miayaar-logo-horizontal\s*\{[\s\S]*-webkit-mask-image:/);
  assert.match(brandCss, /\.header > \.miayaar-brand-lockup,[\s\S]*width: 100vw/);
  assert.match(brandCss, /main > \.miayaar-brand-lockup/);
  assert.match(brandCss, /\.header > \.miayaar-brand-lockup\s*\{[\s\S]*margin-top:\s*-30px[\s\S]*padding-top:\s*0/);
  assert.match(brandCss, /width: min\(100%, 960px\)/);
  assert.match(brandCss, /max-height: 220px/);
  assert.match(brandCss, /@media \(max-width: 640px\)[\s\S]*max-width: 100%/);
  assert.match(brandCss, /\.miayaar-admin-brand\s*\{/);
  for (const source of [accuracyDashboardHtml, marketIntelligenceHtml, exportHtml, calibrationHtml]) assert.match(source, /miayaar-(?:brand-lockup|admin-brand)/);
  assert.match(calibrationHtml, /miayaar-logo-horizontal.*miayaar-horizontal-dark\.png/);
  assert.ok(indexHtml.includes('<script src="/shared/index-calibration-bootstrap.js"></script>'));
  assert.ok(indexHtml.indexOf('/shared/index-accuracy-meta.js') < indexHtml.indexOf('/shared/index-calibration-bootstrap.js'));
  assert.ok(indexHtml.indexOf('/shared/index-calibration-bootstrap.js') < indexHtml.indexOf('/shared/index-market-context.js'));
  assert.doesNotMatch(indexHtml, /let AQAR_ACTIVE_CALIBRATION\s*=/);
  assert.ok(indexAccuracyMetaJs.includes('AQAR_ACTIVE_CALIBRATION = AQAR_CALIBRATION_DEFAULTS.createDefaultCalibrationConfig()'));
  assert.ok(indexAccuracyMetaJs.includes('AQAR_V21_SHADOW_CONFIG = AQAR_V21_SHADOW_MULTIPLIERS.createNeutralConfig()'));
  const calibrationBootstrapJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-calibration-bootstrap.js'), 'utf8');
  assert.ok(calibrationBootstrapJs.includes('async function loadCalibrationConfig()'));
  assert.ok(calibrationBootstrapJs.includes('function getCalibrationForProperty(propertyType)'));
  assert.ok(indexHtml.includes('<script src="/shared/index-runtime-state.js"></script>'));
  assert.ok(indexHtml.indexOf('/shared/index-calibration-bootstrap.js') < indexHtml.indexOf('/shared/index-runtime-state.js'));
  assert.ok(indexHtml.indexOf('/shared/index-runtime-state.js') < indexHtml.indexOf('/shared/index-district-map-core.js'));
  assert.ok(indexHtml.indexOf('/shared/index-district-map-core.js') < indexHtml.indexOf('/shared/index-map-linking-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-map-linking-runtime.js') < indexHtml.indexOf('/shared/index-field-view-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-field-view-runtime.js') < indexHtml.indexOf('/shared/index-map-marker-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-map-marker-runtime.js') < indexHtml.indexOf('/shared/index-gis-fetch-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-gis-fetch-runtime.js') < indexHtml.indexOf('/shared/index-gis-fetch-coordinator.js'));
  assert.ok(indexHtml.indexOf('/shared/index-gis-fetch-coordinator.js') < indexHtml.indexOf('/shared/index-gis-display-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-gis-display-runtime.js') < indexHtml.indexOf('/shared/index-scrape-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-scrape-runtime.js') < indexHtml.indexOf('/shared/index-market-context.js'));
  assert.ok(indexHtml.indexOf('/shared/index-gis-display-runtime.js') < indexHtml.indexOf('/shared/index-market-calculation-helpers.js'));
  assert.ok(indexHtml.indexOf('/shared/index-market-calculation-helpers.js') < indexHtml.indexOf('/shared/index-property-data-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-property-data-runtime.js') < indexHtml.indexOf('/shared/index-sales-approach-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-sales-approach-runtime.js') < indexHtml.indexOf('/shared/index-income-approach-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-income-approach-runtime.js') < indexHtml.indexOf('/shared/index-cost-approach-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-cost-approach-runtime.js') < indexHtml.indexOf('/shared/index-dcf-approach-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-dcf-approach-runtime.js') < indexHtml.indexOf('/shared/index-weighted-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-weighted-runtime.js') < indexHtml.indexOf('/shared/index-market-context.js'));
  assert.ok(indexHtml.indexOf('/shared/index-market-context.js') < indexHtml.indexOf('/shared/index-result-rendering-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-result-rendering-runtime.js') < indexHtml.indexOf('/shared/index-observation-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-observation-runtime.js') < indexHtml.indexOf('/shared/index-run-valuation-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-run-valuation-runtime.js') < indexHtml.indexOf('/shared/index-reset-history-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-reset-history-runtime.js') < indexHtml.indexOf('/shared/index-metadata-ui-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-metadata-ui-runtime.js') < indexHtml.indexOf('/shared/index-dom-bootstrap-runtime.js'));
  assert.ok(indexHtml.indexOf('/shared/index-dom-bootstrap-runtime.js') < indexHtml.indexOf('</body>'));
  assert.ok(indexHtml.indexOf('/shared/index-metadata-ui-runtime.js') < indexHtml.indexOf('/shared/index-district-context.js'));
  assert.ok(indexDcfApproachJs.includes('function dcfApproach(data)'));
  assert.ok(indexWeightedRuntimeJs.includes('function calculateWeightedValue(valuations, propData)'));
  assert.ok(indexResultRenderingJs.includes('function buildDecisionEngineLink(result, propData)'));
  assert.ok(indexResultRenderingJs.includes('function displayEvidenceOnlyState(propData)'));
  assert.ok(indexResultRenderingJs.includes('function displayResult(result, valuations, propData)'));
  assert.ok(indexObservationRuntimeJs.includes('function buildObservationPayload(propData, result)'));
  assert.ok(indexObservationRuntimeJs.includes('async function recordValuationObservation(propData, result)'));
  assert.ok(indexObservationRuntimeJs.includes("fetch('/api/valuation-observation'"));
  assert.ok(indexObservationRuntimeJs.includes("status: verifiedProject ? 'verified-dld' : 'unknown'"));
  assert.ok(indexRunValuationRuntimeJs.includes('function runValuation()'));
  assert.ok(indexRunValuationRuntimeJs.includes('AQAR_PROPERTY_EXTRA_FIELDS.validate(propData)'));
  assert.ok(indexRunValuationRuntimeJs.includes("AQAR_POLICY.getApplicableMethods(propData.propType, 'interactive')"));
  assert.ok(indexRunValuationRuntimeJs.includes('saveToHistory(finalResult, propData)'));
  assert.ok(indexResetHistoryRuntimeJs.includes('function resetAll()'));
  assert.ok(indexResetHistoryRuntimeJs.includes('function saveToHistory(result, propData)'));
  assert.ok(indexResetHistoryRuntimeJs.includes('h.slice(0,5)'));
  assert.ok(indexMetadataUiRuntimeJs.includes('async function loadAccuracyMeta()'));
  assert.ok(indexMetadataUiRuntimeJs.includes('function showToast(msg, dur=3000)'));
  assert.ok(indexMetadataUiRuntimeJs.includes('function onPropertyTypeChange()'));
  assert.ok(indexMetadataUiRuntimeJs.includes("AQAR_POLICY.getPropertyPolicy(type)"));
  assert.ok(indexDomBootstrapRuntimeJs.includes("document.addEventListener('DOMContentLoaded', function()"));
  assert.ok(indexDomBootstrapRuntimeJs.includes('loadCalibrationConfig().finally'));
  assert.ok(indexDomBootstrapRuntimeJs.includes('loadMarketIntelligence()'));
  assert.ok(indexHtml.includes('id="btnLoadFacilities" type="button" disabled aria-busy="false"'));
  assert.ok(indexHtml.indexOf('id="gisMap"') < indexHtml.indexOf('id="btnLoadFacilities"'));
  assert.ok(indexHtml.indexOf('id="btnLoadFacilities"') < indexHtml.indexOf('id="gisResult"'));
  assert.ok(indexGisFetchJs.includes('async function loadNearbyFacilities()'));
  assert.ok(indexPrimaryInteractionsJs.includes("getElementById('btnLoadFacilities')?.addEventListener('click', loadNearbyFacilities)"));
  assert.doesNotMatch(indexMapMarkerJs, /debouncedFetchGISData\(\)/);
  assert.doesNotMatch(indexMapLinkingJs, /debouncedFetchGISData\(\)/);
  assert.doesNotMatch(indexDistrictContextJs, /debouncedFetchGISData\(\)/);
  assert.ok(indexDomBootstrapRuntimeJs.includes('scheduleGISMapInit()'));
  assert.ok(indexMapMarkerJs.includes('function scheduleGISMapInit()'));
  assert.ok(indexMapMarkerJs.includes("'requestIdleCallback' in window"));
  assert.ok(indexMapMarkerJs.includes("script.src = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'"));
  assert.ok(indexMapMarkerJs.includes('script.integrity ='));
  assert.ok(indexMapMarkerJs.includes('if (mapInitialized) return;'));
  assert.ok(indexMapMarkerJs.includes("window.addEventListener('load', scheduleAfterLoad, { once: true })"));
  assert.ok(indexGisFetchCoordinatorJs.includes('sessionStorage'));
  assert.ok(indexGisFetchCoordinatorJs.includes('gisInFlightKey === cacheKey'));
  assert.ok(indexGisFetchCoordinatorJs.includes('gisAbortController.abort()'));
  assert.ok(indexWeightedRuntimeJs.includes('AQAR_CALIBRATION_ENGINE.combineMethodResults'));
  assert.ok(indexWeightedRuntimeJs.includes('AQAR_V21_SHADOW_MULTIPLIERS.compute(propData, shadowConfig)'));
  assert.ok(indexCostApproachJs.includes('function costApproach(data)'));
  assert.ok(indexIncomeApproachJs.includes('function incomeCapitalizationApproach(data)'));
  assert.ok(indexSalesApproachJs.includes('function salesComparisonApproach(data)'));
  assert.ok(indexPropertyDataJs.includes('function collectPropertyData()'));
  assert.ok(indexGisDisplayJs.includes('function displayGISResult(gisData)'));
  assert.ok(indexMarketCalculationJs.includes('function getFallbackPrice(city, district)'));
  assert.ok(indexMarketCalculationJs.includes('function calculateViewMultiplier(viewTypes, propertyType)'));
  assert.ok(indexGisFetchJs.includes('function prepareGISRefresh()'));
  assert.ok(indexGisFetchJs.includes('function debouncedFetchGISData()'));
  assert.ok(indexGisFetchJs.includes('async function fetchPOIsFromOSM(lat, lng, radius = 1000, requestSignal = null)'));
  assert.ok(indexGisFetchCoordinatorJs.includes('async function fetchGISData()'));
  assert.ok(indexGisFetchCoordinatorJs.includes('fetchPOIsFromOSM(a, b, radius, requestSignal)'));
  assert.ok(indexScrapeRuntimeJs.includes('async function scrapeRealData()'));
  assert.ok(indexScrapeRuntimeJs.includes('/.netlify/functions/dld-lookup?${params.toString()}'));
  assert.ok(indexScrapeRuntimeJs.includes('getCurrentEvidenceState(data)'));
  assert.ok(indexFieldViewJs.includes('function updateExtraFieldVisibility()'));
  assert.ok(indexFieldViewJs.includes('function handleViewTypeChange(cb)'));
  assert.ok(indexFieldViewJs.includes('function getSelectedViewTypes()'));
  const districtMapCoreJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-district-map-core.js'), 'utf8');
  assert.ok(districtMapCoreJs.includes('async function loadDistrictCoords()'));
  assert.ok(districtMapCoreJs.includes('function getDistrictCoords(district)'));
  assert.ok(districtMapCoreJs.includes('function escapeMapHtml(value)'));
  assert.doesNotMatch(indexHtml, /const UAE_DISTRICTS = \{/);
  assert.doesNotMatch(indexHtml, /const FALLBACK_COORDS = \{/);
  assert.doesNotMatch(indexHtml, /let districtCoordsMap = \{\}/);
  assert.doesNotMatch(indexHtml, /const MAP_DISTRICT_MATCH_MAX_KM = 1\.5/);
  const runtimeStateJs = fs.readFileSync(path.join(__dirname, '..', 'shared', 'index-runtime-state.js'), 'utf8');
  assert.ok(runtimeStateJs.includes('const UAE_DISTRICTS = {'));
  assert.ok(runtimeStateJs.includes('const FALLBACK_COORDS = {'));
  assert.ok(runtimeStateJs.includes('let districtCoordsMap = {}'));
  assert.ok(runtimeStateJs.includes('const MAP_DISTRICT_MATCH_MAX_KM = 1.5'));
  assert.ok(indexHtml.includes('<script src="/shared/index-market-context.js"></script>'));
  assert.ok(indexHtml.includes('<script src="/shared/index-district-context.js"></script>'));
  assert.ok(indexHtml.includes('<script src="/shared/index-gis-helpers.js"></script>'));
  assert.ok(indexHtml.includes('<script src="/shared/index-primary-interactions.js"></script>'));
  assert.ok(indexPrimaryInteractionsJs.includes("addEventListener('click', runValuation)"));
  assert.ok(indexPrimaryInteractionsJs.includes("addEventListener('change', onPropertyTypeChange)"));
  assert.ok(indexPrimaryInteractionsJs.includes("closest?.('[data-action]')"));
  assert.ok(indexPrimaryInteractionsJs.includes("action !== 'review-inputs' && action !== 'new-valuation'"));
  assert.match(indexResultRenderingJs, /data-action="review-inputs"/);
  assert.match(indexResultRenderingJs, /data-action="new-valuation"/);
  assert.doesNotMatch(indexHtml, /onclick="document\.getElementById\('resultSection'\)/);
  assert.ok(indexDistrictContextJs.includes('async function loadDistrictsFromDLD()'));
  assert.ok(indexDistrictContextJs.includes('function filterDistricts(q)'));
  assert.ok(indexDistrictContextJs.includes('function filterProjectBuildings(q)'));
  assert.doesNotMatch(indexHtml, /function loadDistrictsFromDLD\(\)/);
  assert.doesNotMatch(indexHtml, /function getCalibrationForProperty\(propertyType\)/);
  assert.doesNotMatch(indexHtml, /async function loadCalibrationConfig\(\)/);
  assert.doesNotMatch(indexHtml, /async function loadDistrictCoords\(\)/);
  assert.doesNotMatch(indexHtml, /function getDistrictCoords\(district\)/);
  assert.doesNotMatch(indexHtml, /function escapeMapHtml\(value\)/);
  assert.doesNotMatch(indexHtml, /function updateExtraFieldVisibility\(\)/);
  assert.doesNotMatch(indexHtml, /function handleViewTypeChange\(cb\)/);
  assert.doesNotMatch(indexHtml, /function getSelectedViewTypes\(\)/);
  assert.doesNotMatch(indexHtml, /function prepareGISRefresh\(\)/);
  assert.doesNotMatch(indexHtml, /function debouncedFetchGISData\(\)/);
  assert.doesNotMatch(indexHtml, /async function fetchPOIsFromOSM\(lat, lng, radius = 1000, requestSignal = null\)/);
  assert.doesNotMatch(indexHtml, /async function fetchGISData\(\)/);
  assert.doesNotMatch(indexHtml, /async function scrapeRealData\(\)/);
  assert.doesNotMatch(indexHtml, /function displayGISResult\(gisData\)/);
  assert.doesNotMatch(indexHtml, /function getFallbackPrice\(city, district\)/);
  assert.doesNotMatch(indexHtml, /function calculateViewMultiplier\(viewTypes, propertyType\)/);
  assert.doesNotMatch(indexHtml, /function collectPropertyData\(\)/);
  assert.doesNotMatch(indexHtml, /function salesComparisonApproach\(data\)/);
  assert.doesNotMatch(indexHtml, /function incomeCapitalizationApproach\(data\)/);
  assert.doesNotMatch(indexHtml, /function costApproach\(data\)/);
  assert.doesNotMatch(indexHtml, /function dcfApproach\(data\)/);
  assert.doesNotMatch(indexHtml, /function calculateWeightedValue\(valuations, propData\)/);
  assert.doesNotMatch(indexHtml, /function buildDecisionEngineLink\(result, propData\)/);
  assert.doesNotMatch(indexHtml, /function displayEvidenceOnlyState\(propData\)/);
  assert.doesNotMatch(indexHtml, /function displayResult\(result, valuations, propData\)/);
  assert.doesNotMatch(indexHtml, /function buildObservationPayload\(propData, result\)/);
  assert.doesNotMatch(indexHtml, /async function recordValuationObservation\(propData, result\)/);
  assert.doesNotMatch(indexHtml, /function runValuation\(\)/);
  assert.doesNotMatch(indexHtml, /function resetAll\(\)/);
  assert.doesNotMatch(indexHtml, /function saveToHistory\(result, propData\)/);
  assert.doesNotMatch(indexHtml, /async function loadAccuracyMeta\(\)/);
  assert.doesNotMatch(indexHtml, /function showToast\(msg, dur=3000\)/);
  assert.doesNotMatch(indexHtml, /function onPropertyTypeChange\(\)/);
  assert.doesNotMatch(indexHtml, /document.addEventListener\('DOMContentLoaded', function\(\)/);
  assert.ok(inlineValidatorJs.includes('if (checked !== 0)'));
  assert.ok(inlineValidatorJs.includes('Inline JavaScript blocks are not allowed'));
  assert.doesNotMatch(indexHtml, /function filterDistricts\(q\)/);
  assert.ok(indexGisHelpersJs.includes('function getGISRadiusMeters()'));
  assert.ok(indexGisHelpersJs.includes('function updateGISRadiusContext(radius = getGISRadiusMeters(), count = null)'));
  assert.ok(indexGisHelpersJs.includes('function haversineDistance(lat1, lng1, lat2, lng2)'));
  assert.ok(indexGisHelpersJs.includes('function getFacilityLabel(k)'));
  assert.ok(indexGisHelpersJs.includes('function getFacilityIcon(k)'));
  assert.doesNotMatch(indexHtml, /function getGISRadiusMeters\(\)/);
  assert.doesNotMatch(indexHtml, /function haversineDistance\(lat1, lng1, lat2, lng2\)/);
  assert.doesNotMatch(indexHtml, /onchange="onCityChange\(\)"/);
  assert.doesNotMatch(indexHtml, /onchange="onPropertyTypeChange\(\)"/);
  assert.doesNotMatch(indexHtml, /oninput="updateExtraFieldVisibility\(\)"/);
  assert.doesNotMatch(indexHtml, /onclick="(scrapeRealData|runValuation|resetAll)\(\)"/);
  assert.ok(indexGisDisplayJs.includes('class="gis-impact-label"'));
  assert.ok(indexGisDisplayJs.includes('class="gis-impact-detail"'));
  assert.ok(indexScrapeRuntimeJs.includes('class="market-status-detail"'));
  assert.ok(indexScrapeRuntimeJs.includes('class="market-status-review"'));
  assert.ok(indexMapMarkerJs.includes('class="gis-map-unavailable"'));
  assert.ok(indexMapLinkingJs.includes('class="project-map-label"'));
  assert.ok(indexMapLinkingJs.includes('class="project-map-popup-source"'));
  assert.ok(indexMapLinkingJs.includes('class="project-map-source"'));
  assert.ok(indexHtml.includes('class="gis-facilities-title"'));
  assert.ok(indexHtml.includes('class="gis-facilities-list"'));
  assert.ok(indexHtml.includes('class="gis-score-display"'));
  assert.ok(indexHtml.includes('class="gis-map-container"'));
  assert.ok(indexMapMarkerJs.includes('class="poi-popup-distance"'));
  assert.ok(indexMapMarkerJs.includes("const poiClass = colors[p.type] ? `poi-${p.type}` : 'poi-default';"));
  assert.ok(indexMapMarkerJs.includes('class="poi-marker ${poiClass}"'));
  assert.ok(indexMapMarkerJs.includes('function updateMapMarker(lat, lng)'));
  assert.ok(indexMapMarkerJs.includes('function addPOIsToMap(pois)'));
  assert.ok(indexMapMarkerJs.includes('function initGISMap()'));
  assert.ok(indexMapLinkingJs.includes('async function resolveDistrictCoords(district)'));
  assert.ok(indexMapLinkingJs.includes('async function selectDistrict(d)'));
  assert.ok(indexMapLinkingJs.includes('function updateDistrictFromMapPoint(lat, lng)'));
  assert.doesNotMatch(indexHtml, /class="poi-marker" style="--poi-color:/);
  assert.ok(indexPageCss.includes('.observation-status.success'));
  assert.ok(indexPageCss.includes('.observation-status.warning'));
  assert.ok(indexResultRenderingJs.includes('class="result-method-status ${statusClass}"'));
  assert.doesNotMatch(indexHtml, /status\.style\.color/);
  assert.doesNotMatch(indexHtml, /<b style="color:\$\{color\};font-size:10px">/);
  assert.doesNotMatch(indexHtml, /<div style="background:#d4920e;color:#06111d/);
  assert.doesNotMatch(indexHtml, /<div style="background:\$\{colors\[p\.type\]/);
  assert.doesNotMatch(indexHtml, /<div style="font-size:12px;font-weight:700;color:var\(--gold\);margin-bottom:6px">📊 Nearby Facilities<\/div>/);
  assert.doesNotMatch(indexHtml, /id="gisFacilitiesList"[^>]+style="font-size:11px;color:var\(--muted\);line-height:1\.8"/);
  assert.doesNotMatch(indexHtml, /id="gisMap"[^>]+style="margin-top:10px;height:320px/);
  assert.doesNotMatch(indexHtml, /<span style="font-size:10px;color:#888;">\$\{\(p\.distance\*1000\)/);
  assert.match(indexPageCss, /\.js-hidden \{ display: none; \}/);
  assert.match(indexHtml, /<div class="section js-hidden" id="propertyExtraSection">/);
  assert.match(indexFieldViewJs, /currentYear - yearBuilt > 5/);
  assert.match(indexFieldViewJs, /olderThanFiveYears && \(visibility\.bua \|\| visibility\.plotArea \|\| visibility\.renovationYear\)/);
  assert.match(indexHtml, /<div class="row js-hidden" id="rowPropertyAreas">/);
  assert.match(indexHtml, /<div class="row js-hidden" id="rowProjectBuilding">/);
  assert.match(indexHtml, /<div class="row js-hidden" id="gisCoordsRow"/);
  assert.doesNotMatch(indexHtml, /(?:rowPropertyAreas|fgBua|fgPlotArea|fgLastRenovation|rowProjectBuilding|gisCoordsRow)"[^>]+style="display:none"/);
  assert.doesNotMatch(indexHtml, /getElementById\('(rowPropertyAreas|fgBua|fgPlotArea|fgLastRenovation|rowProjectBuilding|gisCoordsRow)'\)\.style\.display/);
  assert.match(indexPageCss, /\.gis-result-panel\.is-visible \{ display: block; \}/);
  assert.match(indexPageCss, /\.gis-project-label\.is-visible \{ display: block; \}/);
  assert.match(indexGisDisplayJs, /container\.classList\.add\('is-visible'\)/);
  assert.doesNotMatch(indexHtml, /(?:gisResult|gisProjectLabel).*style\.display/);
  assert.doesNotMatch(indexDistrictContextJs, /row\.style\.display = visibility\.projectBuilding/);
  assert.match(indexPageCss, /\.autocomplete-list\.is-visible \{ display: block; \}/);
  assert.match(indexPageCss, /\.autocomplete-list \.item\.empty-state \{ color: var\(--muted\); cursor: default; \}/);
  assert.match(indexPageCss, /\.project-building-notice\.attention \{ color: var\(--gold\); \}/);
  assert.match(indexPageCss, /\.project-building-notice\.verified \{ color: var\(--green\); \}/);
  assert.ok(indexDistrictContextJs.includes("function setProjectBuildingNotice(notice, text, tone)"));
  assert.ok(indexDistrictContextJs.includes("empty.className = 'item empty-state'"));
  assert.doesNotMatch(indexDistrictContextJs, /notice\.style\.color|empty\.style\.cssText/);
  assert.doesNotMatch(indexDistrictContextJs, /list\.style\.display|c\.style\.display/);
  assert.doesNotMatch(indexHtml, /scoreDisplay\.innerHTML = `?[^`]*style="color:var\(--gold\)"/);
  assert.doesNotMatch(indexHtml, /<span style="color:var\(--muted\)">🔍 Checking market data/);
  assert.ok(indexMarketContextJs.includes('function buildMarketContextHTML(result, propData)'));
  assert.ok(indexMarketContextJs.includes('class="market-indicators"'));
  assert.doesNotMatch(indexMarketContextJs, /<div style="margin-top:12px;padding-top:10px/);
  assert.match(indexPageCss, /\.market-indicators \{ margin-top: 12px; padding-top: 10px; border-top: 1px solid rgba\(255,255,255,0\.08\); \}/);
  assert.match(indexPageCss, /width: var\(--confidence-width, 0%\)/);
  assert.ok(indexResultRenderingJs.includes("style.setProperty('--confidence-width', `${result.confidencePct}%`)"));
  assert.doesNotMatch(indexHtml, /style="(?:--confidence-width|width):/);
  assert.ok(indexMarketContextJs.includes('function renderEvidenceState(state, container, detail = \'\')'));
  assert.ok(indexMarketContextJs.includes('escapeMapHtml(propData.district || \'the selected area\')'));
  assert.doesNotMatch(indexHtml, /function buildMarketContextHTML\(result, propData\)/);
  assert.ok(accuracyDashboardHtml.includes('<h1 class="miayaar-page-title">Accuracy Dashboard</h1>'));
  assert.ok(accuracyDashboardHtml.includes('<script src="/shared/accuracy-dashboard.js"></script>'));
  assert.ok(accuracyDashboardCss.includes('.refresh-bar-heading'));
  assert.ok(accuracyDashboardCss.includes('.refresh-actions'));
  assert.ok(accuracyDashboardCss.includes('.dashboard-footer-links'));
  assert.ok(accuracyDashboardCss.includes('.table-ref-cell'));
  assert.ok(accuracyDashboardCss.includes('.table-date-cell'));
  assert.doesNotMatch(accuracyDashboardHtml, /<[^>]+style="/);
  assert.ok(accuracyDashboardHtml.includes('id="loadSavedDataButton"'));
  assert.doesNotMatch(accuracyDashboardHtml, /<script>\s*[\s\S]*<\/script>/);
  assert.ok(accuracyDashboardJs.includes('function updateTable(properties)'));
  assert.ok(accuracyDashboardJs.includes("document.getElementById('loadSavedDataButton')?.addEventListener"));
  assert.ok(accuracyDashboardJs.includes('class="loading loading-error"'));
  assert.ok(accuracyDashboardJs.includes('class="table-ref-cell"'));
  assert.ok(accuracyDashboardJs.includes('class="table-city-cell"'));
  assert.ok(accuracyDashboardJs.includes('class="table-date-cell"'));
  assert.ok(accuracyDashboardJs.includes('class="table-summary"'));
  assert.doesNotMatch(accuracyDashboardJs, /style="/);
  assert.ok(calibrationHtml.includes('<script src="/shared/calibration.js"></script>'));
  assert.doesNotMatch(calibrationHtml, /<script>\s*[\s\S]*<\/script>/);
  assert.doesNotMatch(calibrationHtml, /onclick=/);
  assert.ok(calibrationJs.includes('async function request(method=\'GET\', body)'));
  assert.ok(calibrationJs.includes('data-action="add-project-multiplier"'));
  assert.ok(calibrationJs.includes("$('saveButton').addEventListener('click', saveConfig)"));
  assert.ok(calibrationCss.includes('.project-multiplier-row'));
  assert.ok(calibrationCss.includes('.shadow-project-row'));
  assert.ok(calibrationCss.includes('.shadow-band-row'));
  assert.ok(calibrationCss.includes('.shadow-add-row'));
  assert.ok(calibrationCss.includes('.calibration-input-row'));
  assert.ok(calibrationCss.includes('.calibration-group-heading'));
  assert.ok(calibrationJs.includes('class="field-grid shadow-project-row"'));
  assert.ok(calibrationJs.includes('class="field-grid shadow-band-row"'));
  assert.ok(calibrationJs.includes('class="field-grid shadow-add-row"'));
  assert.ok(calibrationJs.includes('class="calibration-input-row"'));
  assert.ok(calibrationJs.includes('class="panel-note calibration-group-heading"'));
  assert.ok(calibrationJs.includes("wrapper.className = 'field-grid project-multiplier-row'"));
  assert.doesNotMatch(calibrationJs, /style="(?:grid-template-columns|display)/);
  assert.doesNotMatch(calibrationJs, /style\.cssText/);
  assert.ok(marketIntelligenceHtml.includes('<h1 class="miayaar-page-title">Market Intelligence</h1>'));
  assert.ok(marketIntelligenceHtml.includes('<script src="/shared/market-intelligence.js"></script>'));
  assert.ok(marketIntelligenceCss.includes('.methodology-panel'));
  assert.ok(marketIntelligenceCss.includes('.dashboard-footer-links'));
  assert.doesNotMatch(marketIntelligenceHtml, /<[^>]+style="/);
  assert.doesNotMatch(marketIntelligenceHtml, /<script>\s*[\s\S]*<\/script>/);
  assert.ok(marketIntelligenceJs.includes('function renderInvestmentTable()'));
  assert.ok(marketIntelligenceJs.includes("document.getElementById('growthPeriodFilter').addEventListener"));
  assert.ok(marketIntelligenceJs.includes('class="loading loading-error"'));
  assert.doesNotMatch(marketIntelligenceJs, /style="/);
  assert.ok(exportHtml.includes('<h1 class="miayaar-page-title">Data Export</h1>'));
  assert.match(exportHtml, /<meta name="viewport" content="width=device-width, initial-scale=1\.0">/);
  assert.ok(exportHtml.includes('<script src="/shared/export.js"></script>'));
  assert.ok(exportHtml.includes('id="exportCsvButton"'));
  assert.ok(exportHtml.includes('id="exportJsonButton"'));
  assert.doesNotMatch(exportHtml, /<script>\s*[\s\S]*<\/script>/);
  assert.ok(exportJs.includes('function csvCell(value)'));
  assert.ok(exportJs.includes("typeof value === 'string'"));
  assert.ok(exportJs.includes("safeText.replace(/\"/g, '\"\"')"));
  assert.ok(exportJs.includes("/^[=+\\-@]/.test(text)"));
  assert.ok(exportJs.includes('class="accuracy-value"'));
  assert.ok(exportCss.includes('.stats .accuracy-value'));
  assert.ok(exportHtml.includes('class="dashboard-link"'));
  assert.doesNotMatch(exportJs, /<b style="color:#00b86e">/);
  assert.doesNotMatch(exportHtml, /href="\/accuracy-dashboard" style=/);
});

test('Market Intelligence tables stay intact inside horizontally scrollable cards', () => {
  assert.match(marketIntelligenceCss, /\.table-scroll/);
  assert.match(marketIntelligenceCss, /overflow-x: auto/);
  assert.match(marketIntelligenceCss, /\.table-scroll table \{ min-width: 520px; \}/);
  assert.match(marketIntelligenceJs, /role="region" tabindex="0" aria-label="Top 10 Investment Districts table"/);
  assert.doesNotMatch(marketIntelligenceHtml, /\.table-scroll thead \{/);
  assert.doesNotMatch(marketIntelligenceHtml, /data-label="District"/);
});
